Update add listing image

diff --git a/.github/workflows/add-listing-image.yaml b/.github/workflows/add-listing-image.yaml
--- a/.github/workflows/add-listing-image.yaml
+++ b/.github/workflows/add-listing-image.yaml
@@ -50,10 +50,14 @@ jobs:
 
       - name: Update XML listing
         run: |
-          exit 5
           item_number="${{ github.event.issue.title }}"
           body="${{ github.event.issue.body }}"
-          img_url=$(echo "$body" | grep -oP 'src="\K[^"]+')
+          if [[ "$body" =~ src=\"([^\"]+)\" ]]; then
+            img_url="${BASH_REMATCH[1]}"
+          else
+            echo "Error: No image URL found in the issue body."
+            exit 1
+          fi
 
           echo "Debugging: img_url: $img_url"
 
